apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{ .Values.app.name }}-deployment"
  labels:
    app: {{ .Values.app.name }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      app: {{ .Values.app.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.app.name }}
    spec:
      containers:
        - name: {{ .Values.app.name }}
          image: "{{ .Values.registry.repository }}/{{ .Values.registry.image }}:{{ .Values.registry.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.registry.pullPolicy }}
          ports:
            - containerPort: 8000
          env:
            - name: db_root_password
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.dbsecrets.secretsname }}
                  key: db_root_password
            - name: database
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.dbsecrets.secretsname }}
                  key: database