---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{ .Values.db.name }}-deployment"
  labels:
    app: {{ .Values.db.name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.db.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.db.name }}
    spec:
      containers:
      - name: "{{ .Values.db.name }}-{{ .Values.app.name }}"
        image: "{{ .Values.dbregistry.image }}:{{ .Values.dbregistry.tag }}"
        imagePullPolicy: {{ .Values.dbregistry.pullPolicy }}
        env:
        - name: POSTGRES_DB
          valueFrom:
            secretKeyRef:
              name: {{ .Values.dbsecrets.secretsname }}
              key: database
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: {{ .Values.dbsecrets.secretsname }}
              key: db_user
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ .Values.dbsecrets.secretsname }}
              key: db_root_password
        ports:
        - containerPort: 5432
          name: db-container
        volumeMounts:
          - name: postgres-persistent-storage
            mountPath: /var/lib/postgresql/data
      volumes:
        - name: postgres-persistent-storage
          persistentVolumeClaim:
            claimName: postgres-pv-claim